events {}

http {
    upstream product_service {
	server product-service:5000;
    }

    upstream order_service {
	server order-service:5000;
    }

    upstream user_service {
	server user-service:5000;
    }

    server {
	listen 80;

	# CORS
	add_header Access-Control-Allow-Origin *;
	add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
	add_header Access-Control-Allow-Headers "Content-Type, Authorization";

	# Preflight
	location / {
            if ($request_method = OPTIONS) {
		add_header Access-Control-Allow-Origin *;
		add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
		add_header Access-Control-Allow-Headers "Content-Type, Authoritzation";
		return 204;
	    }
	}

	# Healthcheck
	location /health {
	    return 200 "OK";
	}

	# Productes
	location /order {
	    proxy_pass http://product_service;
	}

	# Comandes
	location /order {
	    proxy_pass http://order_service;
	}

	# Usuaris
	location /login {
	    proxy_pass http://user_service;
	}
    }
}
