events {}

http {
    # -------------------------
    # UPSTREAMS
    # -------------------------
    upstream user_service {
        server user-service:5000;
    }

    upstream product_service {
        server product-service:5000;
    }

    upstream order_service {
        server order-service:5000;
    }

    # -------------------------
    # SERVER
    # -------------------------
    server {
        listen 80;

        # -------------------------
        # CORS GLOBAL
        # -------------------------
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;

        # Preflight (ara sí, dins del bloc server)
        if ($request_method = OPTIONS) {
            return 204;
        }

        # Healthcheck
        location /health {
            return 200 "OK";
        }

        # LOGIN → user-service
        location /login {
            proxy_pass http://user_service;
        }

        # PRODUCTS → product-service
        location /products {
            proxy_pass http://product_service;
        }

        # ORDER → order-service
        location /order {
            proxy_pass http://order_service;
        }
    }
}
